apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: db
        image: postgres:14.0
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 5432
        env:
        - name: DB_PASSWORD
          valueFrom:
            name: db-password
            key: DB_PASSWORD
        - name: db-configuraiton
          configMapRef:
            name: db-config
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: db-pv-volume
      volumes:
        - name: db-pv-volume
          persistentVolumeClaim:
            claimName: db-pv-claim