apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: db
        image: postgres:14.0
        imagePullPolicy: "IfNotPresent"
        securityContext:
          runAsUser: 0
        ports:
          - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: POSTGRES_DB
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: db-pv-volume
      volumes:
        - name: db-pv-volume
          persistentVolumeClaim:
            claimName: db-pv-claim