apiVersion: apps/v1
kind: Deployment
metadata:
  name: logicaldoc
spec:
  selector:
    matchLabels:
      app: logicaldoc
  template:
    metadata:
      labels:
        app: logicaldoc
    spec:
      containers:
        - name: logicaldoc
          image: logicaldoc/logicaldoc-ce:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: POSTGRES_PASSWORD
          envFrom:
          - configMapRef:
              name: ld-config
          volumeMounts:
          - mountPath: /LogicalDoc/conf
            name: ldoc-conf-v
          - mountPath: /LogicalDoc/repository
            name: ldoc-repository-v
            
      volumes:
      - name: ldoc-conf-v
        persistentVolumeClaim:
            claimName: ldoc-conf-claim
      - name: ldoc-repository-v
        persistentVolumeClaim:
          claimName: ldoc-repository-claim