apiVersion: apps/v1
kind: Deployment
metadata:
  name: logicaldoc
spec:
  selector:
    matchLabels:
      app: logicaldoc
  template:
    metadata:
      labels:
        app: logicaldoc
    spec:
      containers:
        - name: logicaldoc
          image: denizh2412/ld:latest
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: ld-config
              mountPath: /home/logicaldoc/conf/context.properties
              subPath: context.properties
      volumes:
        - name: ld-config
          configMap:
            name: ld-config
            