apiVersion: apps/v1
kind: Deployment
metadata:
  name: logicaldoc
spec:
  selector:
    matchLabels:
      app: logicaldoc
  template:
    metadata:
      labels:
        app: logicaldoc
    spec:
      containers:
      - name: logicaldoc
        image: denizh2412/ld:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
