---
- name: Setup worker
  hosts: worker
  become: true
  vars_files:
   - vars/worker_vars.yml
  roles:
    - role-docker

#Playbook only installs docker on the worker machine and everything required to run it