---
# Jenkins service name
jenkins_master_service: jenkins

# Jenkins user and group
jenkins_master_user: jenkins

# Name and password for the Jenkins admin user
jenkins_master_admin_name: admin
jenkins_master_admin_pass: admin

# Authorization strategy [full_once_logged|matrix]
# (the matrix flag requires the "matrix-auth" plugin)
jenkins_master_authorization_strategy: full_once_logged


# Values of the default config options
jenkins_master_config_jenkins_home: /var/lib/jenkins
jenkins_master_config_jenkins_java_cmd: ""
jenkins_master_config_jenkins_user: "{{ jenkins_master_user }}"
jenkins_master_config_jenkins_java_options__default: -Djava.awt.headless=true
jenkins_master_config_jenkins_java_options__custom: ""
jenkins_master_config_jenkins_java_options: "{{
  [
    jenkins_master_config_jenkins_java_options__default,
    jenkins_master_config_jenkins_java_options__custom
  ] | join(' ') }}"
jenkins_master_config_jenkins_port: 8080
jenkins_master_config_jenkins_listen_address: 52.174.150.54
jenkins_master_config_jenkins_https_port: ""
jenkins_master_config_jenkins_https_keystore: ""
jenkins_master_config_jenkins_https_keystore_password: ""
jenkins_master_config_jenkins_https_listen_address: ""
jenkins_master_config_jenkins_ajp_port: ""
jenkins_master_config_jenkins_ajp_listen_address: ""
jenkins_master_config_jenkins_debug_level: 5
jenkins_master_config_jenkins_enable_access_log: "no"
jenkins_master_config_jenkins_handler_max: 100
jenkins_master_config_jenkins_handler_idle: 20
jenkins_master_config_jenkins_args: ""

# Default config options
jenkins_master_config__default:
  jenkins_home: "{{ jenkins_master_config_jenkins_home }}"
  jenkins_java_cmd: "{{ jenkins_master_config_jenkins_java_cmd }}"
  jenkins_user: "{{ jenkins_master_config_jenkins_user }}"
  jenkins_java_options: "{{ jenkins_master_config_jenkins_java_options }}"
  jenkins_port: "{{ jenkins_master_config_jenkins_port }}"
  jenkins_listen_address: "{{ jenkins_master_config_jenkins_listen_address }}"
  jenkins_https_port: "{{ jenkins_master_config_jenkins_https_port }}"
  jenkins_https_keystore: "{{ jenkins_master_config_jenkins_https_keystore }}"
  jenkins_https_keystore_password: "{{ jenkins_master_config_jenkins_https_keystore_password }}"
  jenkins_https_listen_address: "{{ jenkins_master_config_jenkins_https_listen_address }}"
  jenkins_ajp_port: "{{ jenkins_master_config_jenkins_ajp_port }}"
  jenkins_ajp_listen_address: "{{ jenkins_master_config_jenkins_ajp_listen_address }}"
  jenkins_debug_level: "{{ jenkins_master_config_jenkins_debug_level }}"
  jenkins_enable_access_log: "{{ jenkins_master_config_jenkins_enable_access_log }}"
  jenkins_handler_max: "{{ jenkins_master_config_jenkins_handler_max }}"
  jenkins_handler_idle: "{{ jenkins_master_config_jenkins_handler_idle }}"
  jenkins_args: "{{ jenkins_master_config_jenkins_args }}"

# Custom config options
jenkins_master_config__custom: {}

# Final Jenkins config
jenkins_master_config: "{{
  jenkins_master_config__default.update(jenkins_master_config__custom) }}{{
  jenkins_master_config__default }}"


# Final list of plugins 
jenkins_master_plugins: {}


# Default plugin module params
jenkins_master_plugins_params__default:
  url_username: "{{ jenkins_master_admin_name }}"
  url_password: "{{ jenkins_master_admin_pass }}"
  url: http://{{ jenkins_master_config_jenkins_listen_address }}:{{ jenkins_master_config_jenkins_port }}

# Custom plugin module params
jenkins_master_plugins_params__custom: {}

# Final plugin module params
jenkins_master_plugins_params: "{{
  jenkins_master_plugins_params__default.update(jenkins_master_plugins_params__custom) }}{{
  jenkins_master_plugins_params__default }}"