pipeline{
    agent any
    post{
        always{
            echo 'Pipeline complete'
        }
        failure{
            echo 'Pipeline failed'
        }
        success{
            echo 'Pipeline successfull'
        }
    }

    stages{
        stage("Checkout"){
            steps{
                echo 'load'
            }
        }

        stage("Building Parallel"){
            when {
                branch 'main'
            }
            failFast true    
            parallel{
                stage('Java 8'){
                    steps{
                        echo 'Building with Java 8'
                        }
                }   
                stage('Java 11'){
                    steps{
                        echo 'Building with Java 11'
                         }
                }
                stage('Java 17'){
                    steps{
                        echo 'Building with Java 17 but only after Java 11 is completed and successfully'
                         }
                }



                }
                 
       }}  
            }

            }
        
