#Database configmap with basic ENV vars required to install a postgresdb

apiVersion : v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: default
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
