#Logicaldoc configmap containing credentials to db, url and installation parameters. Minimum needed memory is  1000MB (unit is expressed in MB)
apiVersion : v1
kind: ConfigMap
metadata:
  name: ld-config
  namespace: default
  labels:
    app: logicaldoc
data:
  LDOC_VERSION: "8.7.3"
  LDOC_MEMORY: "2500"
  DEBIAN_FRONTEND: "noninteractive"
  CATALINA_HOME: "/opt/logicaldoc/tomcat"
  DB_ENGINE: "postgres"
  DB_MANUALURL: "true"
  DB_URL: "jdbc:postgresql://db:5432/postgres"
  DB_USER: admin