apiVersion : v1
kind: ConfigMap
metadata:
  name: ld-config
  namespace: default
  labels:
    app: logicaldoc
data:
  context.properties:
    jdbc.dbms=postgres
    jdbc.driver=org.postgresql.Driver
    jdbc.password=${POSTGRES_PASSWORD}
    jdbc.username=${POSTGRES_USER}
    jdbc.url=jdbc.url=jdbc:postgresql://${DB_SERVICE_HOST}:5432/logicaldoc
    jdbc.cp=dbcp